name: Speed Test
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  main:
    name: SpeedTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create logs directory
        run: mkdir -p logs
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Run PHP processor
        run: php Files/vmess_processor.php > logs/php_run.log 2>&1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Tehran'
      - name: Install cython
        run: pip install cython
      - name: Install Requirements
        run: |
          pip install speedtest-cli
          pip install -r ./utils/requirements.txt > logs/pip_install.log 2>&1
      - name: Create output directories
        run: mkdir -p ./sub/splitted ./utils/speedtest ./logs
      - name: Download merge3.txt
        run: wget -O ./bulk/merge3.txt https://raw.githubusercontent.com/tinde29/Config_Collector/main/bulk/merge3.txt || echo "Failed to download merge3.txt"
      - name: Run Lite Speedtest
        run: |
          sh ./utils/speedtest/speedtest2.sh
          python ./utils/speedtest/output.py > logs/output_py.log 2>&1
      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Allconfig Base64.txt V2.txt ./sub/sub_merge.txt ./sub/sub_merge_base64.txt LogInfo.txt ./sub/splitted/* ./bulk/*
          git commit -m "☠️ $(date '+%Y-%m-%d %H:%M:%S') Speed Test" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main
